---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: sudo apt-get update
run:
  path: sudo apt-get install -y git
run:
  path: source-code/build.sh