---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 'latest'

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: source-code/build.sh