---
resources:
  - name: source-code
  type: git
  source:
    uri: https://github.com/gradle/gradle-build-scan-quickstart
    branch: test

jobs:
  - name: job-hello-world
    public: true
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: build.sh
